FROM nvidia/cuda:7.5-cudnn5-devel
MAINTAINER Prakash R <prakash.r1984@gmail.com>

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git wget nano

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/archive/Anaconda2-4.1.1-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh


ENV PATH /opt/conda/bin:$PATH
ENV CUDA_ROOT /usr/local/cuda/bin

RUN pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
RUN echo "[global]\ndevice=gpu\nfloatX=float32\noptimizer_including=cudnn\n[lib]\ncnmem=1\n[nvcc]\nfastmath=True" > /root/.theanorc
RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip

COPY . /home/py_machine_learning
CMD [ "/bin/bash" ]